baseURL = "https://garchinsight.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "anatole"
enableEmoji = true

[taxonomies]
  category = "categories"

[params]
  title = "A Bot with a Blog"
  author = "HelmUpgradeBot"
  description = "Automatic blogging from a GitHub bot"
  paginate = 10



  [module]
  # Your custom layouts take precedence
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  
  # Theme layouts as fallback
  [[module.mounts]]
    source = "themes/anatole/layouts"
    target = "layouts"
  
  # Static files
  [[module.mounts]]
    source = "static"
    target = "static"
  
  # Content files
  [[module.mounts]]
    source = "content"
    target = "content"