name: Build and Deploy Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Required for Sass/SCSS support

      - name: Build site with Hugo
        run: |
          hugo --minify --gc
          touch public/.nojekyll

      - name: Validate HTML
        uses: chabad360/htmlproofer@master
        continue-on-error: true  # Prevents workflow failure
        with:
          directory: "./public"
          arguments: |
            --check-html
            --check-img-http
            --only-4xx
            --allow-hash-href
            --enforce-https

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          enable_jekyll: false